export const fonts: string[] = [
  "'Courier New', monospace",
  "'Arial', sans-serif",
  "'Georgia', serif",
  "'Times New Roman', serif",
  "'Verdana', sans-serif",
  "Manrope",
  "Poppins",
  "Space Grotesk",
  "DM Sans",
  "Playfair Display",
  "Playwrite IN Guides",
  "Dancing Script",
  "Lobster",
];
